services:
  app:
    depends_on:
      - 'mysql'
    build: .
    ports:
      - '$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT'
    restart: 'on-failure'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/alura_challenge_db'
      - 'SPRING_DATASOURCE_USERNAME=${MYSQL_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}'
    volumes:
      - '.:/app'
    tty: true
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
    ports:
      - '${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}'
    volumes:
      - 'mysql:/var/lib/mysql'

volumes:
  mysql: