spring:
  application:
    name: AluraChallenge
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off
  flyway:
    locations: classpath:db/migration
    enabled: true

server:
  port: 8080